### ISSUE TITLE
Tablica AirQuality_pollutants

### ISSUE THREAD

**Issue by ispeh** [lfaktor3/Kvaliteta_Zraka#5]
Kreirati tablicu AirQuality_pollutants sa kolonama POLLUTANT_ID, POLLUTANT_NAME

**Comment by lfaktor3** [comment]
![image](https://user-images.githubusercontent.com/25528023/33942389-11a000e6-e016-11e7-82d8-b2fe8ea35bfe.png)

Evo prvog problema...

**Comment by lfaktor3** [comment]
Resetirao sam laptop i ponovno se spojio na bazu, radi sada.
